plugins {\n    id 'java'\n    id 'org.springframework.boot' version '3.2.0'\n    id 'io.spring.dependency-management' version '1.1.4'\n} \ngroup = 'com.opik'\nversion = '0.0.1-SNAPSHOT'\nsourceCompatibility = '21'\n\nrepositories {\n    mavenCentral()\n} \ndependencies {\n    implementation 'org.springframework.boot:spring-boot-starter-web'\n    implementation 'org.springframework.boot:spring-boot-starter-actuator'\n    testImplementation 'org.springframework.boot:spring-boot-starter-test'\n} \ntasks.named('test') {\n    useJUnitPlatform()\n}